# Generated by Django 5.1.1 on 2024-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=60)),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=60)),
            ],
        ),
    ]
