# Generated by Django 5.1.1 on 2024-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
