# Generated by Django 5.1.1 on 2024-10-09 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_solicitudes_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('placeholder', 'Nada'), ('Matematicas', 'Matematicas'), ('Paleontologia', 'Paleontologia'), ('Restauracion', 'Restauracion'), ('Digitalizacion', 'Digitalizacion'), ('libritos', 'Libreria'), ('Novelas', 'Novelas'), ('cuentos', 'Cuentos')], default='placeholder', max_length=60),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='departamento',
            field=models.CharField(choices=[('placeholder', 'Nada'), ('Matematicas', 'Matematicas'), ('Paleontologia', 'Paleontologia'), ('Restauracion', 'Restauracion'), ('Digitalizacion', 'Digitalizacion'), ('libritos', 'Libreria'), ('Novelas', 'Novelas'), ('cuentos', 'Cuentos')], default='placeholder', max_length=60),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
