# Generated by Django 5.1.1 on 2024-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_personal_name_alter_personal_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'ordering': ['departamento']},
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='prioridad',
            field=models.CharField(choices=[('Muy Importante', 'Muy Importante'), ('Importante', 'Importante'), ('Poco Importante', 'Poco Importante')], default='Importante', max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='departamento',
            field=models.CharField(choices=[('placeholder', 'Seleccionar'), ('Matematicas', 'Matematicas'), ('Paleontologia', 'Paleontologia'), ('Restauracion', 'Restauracion'), ('Digitalizacion', 'Digitalizacion'), ('libritos', 'Libreria'), ('Novelas', 'Novelas'), ('cuentos', 'Cuentos')], default='placeholder', max_length=60),
        ),
    ]
