# Generated by Django 3.1.2 on 2024-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0006_auto_20241115_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='autor',
            field=models.CharField(default='anónimo', max_length=60),
        ),
    ]
