# Generated by Django 3.1.2 on 2024-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0007_solicitudes_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='num_sistema',
            field=models.CharField(default='sin información', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='plazo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='ubicación',
            field=models.CharField(default='sin información', max_length=20),
        ),
    ]
