# Generated by Django 3.1.2 on 2024-11-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0009_auto_20241115_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
