# Generated by Django 3.1.2 on 2024-11-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0011_auto_20241115_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sector',
            field=models.CharField(choices=[('placeholder', 'Nada'), ('Extensión Cultural', 'Extensión Cultural'), ('Servicio de atención a usuarios', 'Servicio de atención a usuarios'), ('Conservación', 'Conservación'), ('Digitalización', 'Digitalización'), ('Depósito Legal', 'Depósito Legal'), ('Adquisiciones Bibliográficas', 'Adquisiciones Bibliográficas'), ('Depósito Legal Electrónico', 'Depósito Legal Electrónico'), ('Mapoteca', 'Mapoteca'), ('Láminas y estampas', 'Láminas y estampas'), ('Fotográfico y audiovisual', 'Fotográfico y audiovisual'), ('Periódicos', 'Periódicos'), ('Hemeroteca', 'Hemeroteca'), ('Fondo General', 'Fondo General'), ('Sección Chilena', 'Sección Chilena')], default='placeholder', max_length=60),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='departamento',
            field=models.CharField(choices=[('placeholder', 'Seleccionar'), ('Extensión Cultural', 'Extensión Cultural'), ('Servicio de atención a usuarios', 'Servicio de atención a usuarios'), ('Conservación', 'Conservación'), ('Digitalización', 'Digitalización'), ('Depósito Legal', 'Depósito Legal'), ('Adquisiciones Bibliográficas', 'Adquisiciones Bibliográficas'), ('Depósito Legal Electrónico', 'Depósito Legal Electrónico'), ('Mapoteca', 'Mapoteca'), ('Láminas y estampas', 'Láminas y estampas'), ('Fotográfico y audiovisual', 'Fotográfico y audiovisual'), ('Periódicos', 'Periódicos'), ('Hemeroteca', 'Hemeroteca'), ('Fondo General', 'Fondo General'), ('Sección Chilena', 'Sección Chilena')], default='placeholder', max_length=60),
        ),
    ]
