# Generated by Django 3.1.2 on 2024-11-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0012_auto_20241115_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_publicación',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
