# Generated by Django 3.1.2 on 2024-11-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0013_solicitudes_fecha_publicación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='número_de_sistema',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
