# Generated by Django 3.1.2 on 2024-11-23 00:27

import Cuentas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cuentas', '0016_auto_20241117_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to=Cuentas.models.user_image_upload_to),
            preserve_default=False,
        ),
    ]
